# Generated by Django 5.1.5 on 2025-01-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='about',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='rol1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='rol2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='rol3',
        ),
        migrations.AddField(
            model_name='about',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='freelencer',
            field=models.TextField(default='Freelance information not available', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Link'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technologies',
            field=models.CharField(max_length=200, verbose_name='Technologies'),
        ),
        migrations.AddField(
            model_name='home',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.role'),
        ),
    ]
