# Generated by Django 5.1.5 on 2025-01-31 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_role_remove_about_degree_remove_about_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
    ]
